### ISSUE TITLE
missing syntax highlight

### ISSUE THREAD

**Issue by arkhan** [xahlee/xah-js-mode.el#1]
hello, great work
I have this problem in "∑js" mode, highlight don't work
![Imgur](http://i.imgur.com/GSymnaA.png)

**Comment by xahlee** [comment]
i just tested, starting emacs freshing by
emacs -q
highlight works for me. Can you try that? If that works, then we can take next step. Probably something in your init or conflict with some package.
I'm running emacs 24.5.1
any emacs 24.x should work.

**Comment by xahlee** [comment]
looking at your code, i think it is working, but

1. the color is different from what i have.
2. the mode does not support node.js words, just plain js.

try this

console.log( function () { return 3; });

the console.log should be blue, the function and return should be 3.

screenshot at
http://ergoemacs.org/emacs/xah-js-mode.html

the mode doesn't support node.js keywords though. So, require etc are not highlighted.
It can be easily added though, if you want to try, just find the keyword part and add node.js's words.  If you make pull request, i'll merge.

**Comment by arkhan** [comment]
+1
